site_name: 我的知识库名称
site_url: https://setsuodu.github.io/VideoPlayerApp/
nav: # 定义网站左侧导航栏的结构
    - Home: index.md
    - 概念: concepts/intro.md
    - 项目:
        - Project A: projects/project_a.md
        - Project B: projects/project_b.md

theme:
    name: material # 使用 MkDocs-Material 主题
    # ... 其他主题配置，如颜色、字体等

plugins:
    # 启用搜索功能
    - search:
        lang: en, zh 
    # 如果要处理 Obsidian 链接和特性，需要在这里添加相应插件
    # - mkdocs-for-obsidian
    # - awesome-pages
    - roamlinks
        # 你可能需要配置参数，例如：
        # wikilinks: true  # 确保启用维基链接样式
        # markdown_location: "docs"
markdown_extensions:
    # 支持脚注、表格等
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - tables
    
    # pymdownx 是 MkDocs Material 推荐的高级扩展
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.critic
    - pymdownx.betterem
    - pymdownx.mark
    - pymdownx.inlinehilite
    - pymdownx.keys