name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main # 只有 main 分支有新内容时才触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x # 使用最新的 Python 版本

      - name: Install dependencies
        run: |
          # 使用 mkdocs-roamlinks-plugin 来处理 [[内部链接]]
          pip install mkdocs mkdocs-material mkdocs-roamlinks-plugin
      
      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force # 使用 gh-deploy 命令部署到 gh-pages 分支